services:
  init-db:
    image: alpine
    command: sh -c "mkdir -p /data && [ -f /data/db.sqlite ] || touch /data/db.sqlite"
    volumes:
      - ./data:/data
    depends_on: []

  api:
    image: graymattermetrics/cerebrum
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6060:6060
    volumes:
      - ./data:/data
    depends_on:
      - init-db

  visualisation:
    image: graymattermetrics/visualisation
    build:
      dockerfile: ./visualisation/Dockerfile
    ports:
      - 7070:7070
    volumes:
      - ./data:/data
    depends_on:
      - init-db
    env_file:
      - .env

  sqlite-web:
    image: coleifer/sqlite-web
    platform: linux/amd64
    volumes:
      - ./data:/data
    command: sqlite_web /data/db.sqlite --host 0.0.0.0 --port 8080 --password
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - init-db
