# All units in milliseconds unless otherwise specified
# (^) = Implemented
# (?) = Unclear what this does

information_processing_rate:
    low: 0.5  # Minimum information processing rate
    high: 1.111  # Maximum information processing rate

self_paced:
    number_of_training_rounds: 2  # Number of rounds at the start to get the user used to the test ^
    max_wrong_count: 5  # Number of wrong answers before the test ends ^
    max_right_count: 4  # Number of right answers before self-paced test ends ^

machine_paced:
    max_count: 8  # ?
    max_start_duration: 2100  # Maximum initital `duration` (ignoring `self_paced_average`) ^
    not_there: 0  # ?
    not_there_disabled: true  # ?

    rolls:
        mean_size: 8  # Take the correct answers of the last `mean_size` rounds ^
        threshold: 0.6  # Percentage of correct answers before speeding up / slowing down ^

    blocking:
        no_input_count: 2  # How many rounds with no response to declare a "block"
        slow_display_time_duration: 300  # When there are no responses to two rounds, slow by this amount
        max_display_time_duration: 135  # After blocking, wait for response, then resume with `machine_pace` + this amount
    
    slowdown:
        initial_duration: 75  # Ms slower than `self_paced_average` to start machine_paced ^
        base_duration: 100  # When there is are `max_wrong_count` wrong answers, slow by this amount ^

    speedup:
        base_duration: 33  # When there are `max_right_count` right answers, decrease `duration` by this amount ^
        on_correct: true  # Whether to speed up on correct answers
        on_wrong: false  # Whether to speed up on wrong answers
        on_noinput: false  # Whether to speed up on no input
        base: -25  # ?
        mod: 0  # ?

anti_spoofing:
    max_bad_tests_in_session: 3  # Number of bad tests because retest is no longer an option

tutorial:  # ?
    tutorial_nSPRounds: 12
    tutorial_nMPRounds: 8
    tutorial_mpRoundStartDuration: 2100
    tutorial_mpRoundDurationDelta: -200

# Whether to save round data and have the ability for the user to download it - 
save_round_data: true  # Or to automatically send it to another user

no_response_timeout: 10_000  # Time in milliseconds before the test ends if no response is given ^
max_test_duration: 120_000  # Maximum time in milliseconds before the test ends ^

n_endmode_rounds: 2  # Number of extra rounds at the end of the test

mp_input_ends_round: true  # ?
mp_rt_buffer_size: 3  # ?

bpRoundCount: 3  # ?
n_inversecolordisplay: 3  # ?
p_displayother: 0.25  # ?
p_invert_letnum: 0.25  # ?